require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AcusasController do

  # This should return the minimal set of attributes required to create a valid
  # Acusa. As you add validations to Acusa, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AcusasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all acusas as @acusas" do
      acusa = Acusa.create! valid_attributes
      get :index, {}, valid_session
      assigns(:acusas).should eq([acusa])
    end
  end

  describe "GET show" do
    it "assigns the requested acusa as @acusa" do
      acusa = Acusa.create! valid_attributes
      get :show, {:id => acusa.to_param}, valid_session
      assigns(:acusa).should eq(acusa)
    end
  end

  describe "GET new" do
    it "assigns a new acusa as @acusa" do
      get :new, {}, valid_session
      assigns(:acusa).should be_a_new(Acusa)
    end
  end

  describe "GET edit" do
    it "assigns the requested acusa as @acusa" do
      acusa = Acusa.create! valid_attributes
      get :edit, {:id => acusa.to_param}, valid_session
      assigns(:acusa).should eq(acusa)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Acusa" do
        expect {
          post :create, {:acusa => valid_attributes}, valid_session
        }.to change(Acusa, :count).by(1)
      end

      it "assigns a newly created acusa as @acusa" do
        post :create, {:acusa => valid_attributes}, valid_session
        assigns(:acusa).should be_a(Acusa)
        assigns(:acusa).should be_persisted
      end

      it "redirects to the created acusa" do
        post :create, {:acusa => valid_attributes}, valid_session
        response.should redirect_to(Acusa.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved acusa as @acusa" do
        # Trigger the behavior that occurs when invalid params are submitted
        Acusa.any_instance.stub(:save).and_return(false)
        post :create, {:acusa => {}}, valid_session
        assigns(:acusa).should be_a_new(Acusa)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Acusa.any_instance.stub(:save).and_return(false)
        post :create, {:acusa => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested acusa" do
        acusa = Acusa.create! valid_attributes
        # Assuming there are no other acusas in the database, this
        # specifies that the Acusa created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Acusa.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => acusa.to_param, :acusa => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested acusa as @acusa" do
        acusa = Acusa.create! valid_attributes
        put :update, {:id => acusa.to_param, :acusa => valid_attributes}, valid_session
        assigns(:acusa).should eq(acusa)
      end

      it "redirects to the acusa" do
        acusa = Acusa.create! valid_attributes
        put :update, {:id => acusa.to_param, :acusa => valid_attributes}, valid_session
        response.should redirect_to(acusa)
      end
    end

    describe "with invalid params" do
      it "assigns the acusa as @acusa" do
        acusa = Acusa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Acusa.any_instance.stub(:save).and_return(false)
        put :update, {:id => acusa.to_param, :acusa => {}}, valid_session
        assigns(:acusa).should eq(acusa)
      end

      it "re-renders the 'edit' template" do
        acusa = Acusa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Acusa.any_instance.stub(:save).and_return(false)
        put :update, {:id => acusa.to_param, :acusa => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested acusa" do
      acusa = Acusa.create! valid_attributes
      expect {
        delete :destroy, {:id => acusa.to_param}, valid_session
      }.to change(Acusa, :count).by(-1)
    end

    it "redirects to the acusas list" do
      acusa = Acusa.create! valid_attributes
      delete :destroy, {:id => acusa.to_param}, valid_session
      response.should redirect_to(acusas_url)
    end
  end

end
