require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdocaosController do

  # This should return the minimal set of attributes required to create a valid
  # Adocao. As you add validations to Adocao, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdocaosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all adocaos as @adocaos" do
      adocao = Adocao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:adocaos).should eq([adocao])
    end
  end

  describe "GET show" do
    it "assigns the requested adocao as @adocao" do
      adocao = Adocao.create! valid_attributes
      get :show, {:id => adocao.to_param}, valid_session
      assigns(:adocao).should eq(adocao)
    end
  end

  describe "GET new" do
    it "assigns a new adocao as @adocao" do
      get :new, {}, valid_session
      assigns(:adocao).should be_a_new(Adocao)
    end
  end

  describe "GET edit" do
    it "assigns the requested adocao as @adocao" do
      adocao = Adocao.create! valid_attributes
      get :edit, {:id => adocao.to_param}, valid_session
      assigns(:adocao).should eq(adocao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Adocao" do
        expect {
          post :create, {:adocao => valid_attributes}, valid_session
        }.to change(Adocao, :count).by(1)
      end

      it "assigns a newly created adocao as @adocao" do
        post :create, {:adocao => valid_attributes}, valid_session
        assigns(:adocao).should be_a(Adocao)
        assigns(:adocao).should be_persisted
      end

      it "redirects to the created adocao" do
        post :create, {:adocao => valid_attributes}, valid_session
        response.should redirect_to(Adocao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved adocao as @adocao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Adocao.any_instance.stub(:save).and_return(false)
        post :create, {:adocao => {}}, valid_session
        assigns(:adocao).should be_a_new(Adocao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Adocao.any_instance.stub(:save).and_return(false)
        post :create, {:adocao => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested adocao" do
        adocao = Adocao.create! valid_attributes
        # Assuming there are no other adocaos in the database, this
        # specifies that the Adocao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Adocao.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => adocao.to_param, :adocao => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested adocao as @adocao" do
        adocao = Adocao.create! valid_attributes
        put :update, {:id => adocao.to_param, :adocao => valid_attributes}, valid_session
        assigns(:adocao).should eq(adocao)
      end

      it "redirects to the adocao" do
        adocao = Adocao.create! valid_attributes
        put :update, {:id => adocao.to_param, :adocao => valid_attributes}, valid_session
        response.should redirect_to(adocao)
      end
    end

    describe "with invalid params" do
      it "assigns the adocao as @adocao" do
        adocao = Adocao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Adocao.any_instance.stub(:save).and_return(false)
        put :update, {:id => adocao.to_param, :adocao => {}}, valid_session
        assigns(:adocao).should eq(adocao)
      end

      it "re-renders the 'edit' template" do
        adocao = Adocao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Adocao.any_instance.stub(:save).and_return(false)
        put :update, {:id => adocao.to_param, :adocao => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested adocao" do
      adocao = Adocao.create! valid_attributes
      expect {
        delete :destroy, {:id => adocao.to_param}, valid_session
      }.to change(Adocao, :count).by(-1)
    end

    it "redirects to the adocaos list" do
      adocao = Adocao.create! valid_attributes
      delete :destroy, {:id => adocao.to_param}, valid_session
      response.should redirect_to(adocaos_url)
    end
  end

end
